version: "3.4"

services:
  dockerstocksproducts:
    image: dockerstocksproducts
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 83:8000

  postgres_db:
    image: postgres
    env_file: ./.env
    restart: always

  nginx:
    build: ./nginx

    # web:
    #   image: nginx
    # dockerfile: ./ngix/Dockerfile
    # volumes:
    #   - ./templates:/etc/nginx/templates
    ports:
      - "82:80"
  # volumes:
  #   postgres_data:
